// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkPTH3R7x1bmyxf6I_Xtnzgp4nrlx2xg',
    appId: '1:426688133866:web:ec5738b09d809e6db83593',
    messagingSenderId: '426688133866',
    projectId: 'flutter-app-99609',
    authDomain: 'flutter-app-99609.firebaseapp.com',
    storageBucket: 'flutter-app-99609.appspot.com',
    measurementId: 'G-NP8QM5DH9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIypkubZZ08siuBcM6zVGJxdTXNFXq10Y',
    appId: '1:426688133866:android:ca580b21416cf4adb83593',
    messagingSenderId: '426688133866',
    projectId: 'flutter-app-99609',
    storageBucket: 'flutter-app-99609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmykvlbROFWAR843OD7hbQAoxk0OvYaAM',
    appId: '1:426688133866:ios:298a17389b0319afb83593',
    messagingSenderId: '426688133866',
    projectId: 'flutter-app-99609',
    storageBucket: 'flutter-app-99609.appspot.com',
    iosClientId:
        '426688133866-7c4fokmt9hoj7nrdvrfjpanhfaoq8g37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmykvlbROFWAR843OD7hbQAoxk0OvYaAM',
    appId: '1:426688133866:ios:32beff2bc3f50b4cb83593',
    messagingSenderId: '426688133866',
    projectId: 'flutter-app-99609',
    storageBucket: 'flutter-app-99609.appspot.com',
    iosClientId:
        '426688133866-aidg0rfjrh48bqbqpe88o7t347fpqecf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
